/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransportFleetRouteImport } from './routes/transport.fleet'
import { Route as StaffNewRouteImport } from './routes/staff.new'
import { Route as SecurityLogsRouteImport } from './routes/security.logs'
import { Route as AdminVehiclesRouteImport } from './routes/admin.vehicles'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSummaryRouteImport } from './routes/admin.summary'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as RequestsRouteImport } from './routes/requests.'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportFleetRoute = TransportFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => TransportRoute,
} as any)
const StaffNewRoute = StaffNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StaffRoute,
} as any)
const SecurityLogsRoute = SecurityLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => SecurityRoute,
} as any)
const AdminVehiclesRoute = AdminVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSummaryRoute = AdminSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/security': typeof SecurityRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/transport': typeof TransportRouteWithChildren
  '/requests/': typeof RequestsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/summary': typeof AdminSummaryRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/security/logs': typeof SecurityLogsRoute
  '/staff/new': typeof StaffNewRoute
  '/transport/fleet': typeof TransportFleetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/security': typeof SecurityRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/transport': typeof TransportRouteWithChildren
  '/requests': typeof RequestsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/summary': typeof AdminSummaryRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/security/logs': typeof SecurityLogsRoute
  '/staff/new': typeof StaffNewRoute
  '/transport/fleet': typeof TransportFleetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/security': typeof SecurityRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/transport': typeof TransportRouteWithChildren
  '/requests/': typeof RequestsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/summary': typeof AdminSummaryRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/security/logs': typeof SecurityLogsRoute
  '/staff/new': typeof StaffNewRoute
  '/transport/fleet': typeof TransportFleetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/security'
    | '/staff'
    | '/transport'
    | '/requests/'
    | '/admin/drivers'
    | '/admin/reports'
    | '/admin/summary'
    | '/admin/users'
    | '/admin/vehicles'
    | '/security/logs'
    | '/staff/new'
    | '/transport/fleet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/security'
    | '/staff'
    | '/transport'
    | '/requests'
    | '/admin/drivers'
    | '/admin/reports'
    | '/admin/summary'
    | '/admin/users'
    | '/admin/vehicles'
    | '/security/logs'
    | '/staff/new'
    | '/transport/fleet'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/security'
    | '/staff'
    | '/transport'
    | '/requests/'
    | '/admin/drivers'
    | '/admin/reports'
    | '/admin/summary'
    | '/admin/users'
    | '/admin/vehicles'
    | '/security/logs'
    | '/staff/new'
    | '/transport/fleet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  SecurityRoute: typeof SecurityRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  TransportRoute: typeof TransportRouteWithChildren
  RequestsRoute: typeof RequestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/fleet': {
      id: '/transport/fleet'
      path: '/fleet'
      fullPath: '/transport/fleet'
      preLoaderRoute: typeof TransportFleetRouteImport
      parentRoute: typeof TransportRoute
    }
    '/staff/new': {
      id: '/staff/new'
      path: '/new'
      fullPath: '/staff/new'
      preLoaderRoute: typeof StaffNewRouteImport
      parentRoute: typeof StaffRoute
    }
    '/security/logs': {
      id: '/security/logs'
      path: '/logs'
      fullPath: '/security/logs'
      preLoaderRoute: typeof SecurityLogsRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/admin/vehicles': {
      id: '/admin/vehicles'
      path: '/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/summary': {
      id: '/admin/summary'
      path: '/summary'
      fullPath: '/admin/summary'
      preLoaderRoute: typeof AdminSummaryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDriversRoute: typeof AdminDriversRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSummaryRoute: typeof AdminSummaryRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVehiclesRoute: typeof AdminVehiclesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDriversRoute: AdminDriversRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSummaryRoute: AdminSummaryRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVehiclesRoute: AdminVehiclesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SecurityRouteChildren {
  SecurityLogsRoute: typeof SecurityLogsRoute
}

const SecurityRouteChildren: SecurityRouteChildren = {
  SecurityLogsRoute: SecurityLogsRoute,
}

const SecurityRouteWithChildren = SecurityRoute._addFileChildren(
  SecurityRouteChildren,
)

interface StaffRouteChildren {
  StaffNewRoute: typeof StaffNewRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffNewRoute: StaffNewRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface TransportRouteChildren {
  TransportFleetRoute: typeof TransportFleetRoute
}

const TransportRouteChildren: TransportRouteChildren = {
  TransportFleetRoute: TransportFleetRoute,
}

const TransportRouteWithChildren = TransportRoute._addFileChildren(
  TransportRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  SecurityRoute: SecurityRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  TransportRoute: TransportRouteWithChildren,
  RequestsRoute: RequestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
